#eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://ratel:ratel-123@localhost:2100/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1   #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 2  #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
    status-page-url: http://localhost:${server.port}/swagger-ui.html # ${server.port} 服务的端口号

spring:
  redis:
    host: localhost
    port: 6379
#统一格式
  jackson:
    date-format: yyyy-MM-dd #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期