#swagger http://localhost:ip/swagger-ui.html#!
swagger:
  title: es
  description: es接口文档
  version: 1.0
  basePackage: com.ratel.es.controller

spring:
  redis:
    host: localhost
    port: 6379
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true