
spring:
  datasource:
    url: jdbc:mysql://192.168.147.192:3306/pintuan?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: pintuan
    password: FJAOFbhS0sMzyZzY


#swagger http://localhost:ip/swagger-ui.html#!
swagger:
  title: demo
  description: demo接口文档
  version: 1.0
  basePackage: com.ratel.demo.controller